# http://travis-ci.org/peterbe/django-peterbecom

# This indicates to Travis that we will not use or need sudo
# so that we can benefit from and use the cache->directories
# directive.
sudo: no

language: python

cache: pip

python: 3.5

branches:
  only:
  - master

install:
  - bin/travis/install.sh
before_script:
  - bin/travis/lint.sh
  - bin/travis/setup.sh
script:
  - bin/travis/test.sh
