version: '2'

services:
  db:
    image: postgres:9.5
  memcached:
    image: memcached:1.5
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  redis:
    image: redis:3.2

  # ------------------------------------------------------------------
  # After this point is dev-related services.
  # ------------------------------------------------------------------

  # Base container is used for development tasks like tests, linting, coverage
  # and building docs.
  base:
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   - FRONTEND_SENTRY_PUBLIC_DSN
      #   - CI
    # This builds the tecken:build container
    image: peterbecom:build
    # environment:
    #   - DJANGO_CONFIGURATION
    env_file:
      - .env


  # Web container is a prod-like fully-functioning container.
  web:
    extends:
      service: base
    depends_on:
      - db
      - memcached
      - redis
      - elasticsearch
    ports:
      - "8000:8000"
    links:
      - db
      - memcached
      - redis
      - elasticsearch
    volumes:
      - $PWD:/app
    command: web-dev

  # Container specifically for running tests.
  test:
    extends:
      service: base
    links:
      - db
      - memcached
    command: test

  worker:
    extends:
      service: base
    depends_on:
      - base
    links:
      - db
      - memcached
      - redis
      - elasticsearch
    volumes:
      - $PWD:/app
    command: worker-purge


volumes:
  esdata:
    driver: local
